<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260617233420 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "feed_items" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guid VARCHAR(500) NOT NULL, title TEXT NOT NULL, link TEXT NOT NULL, description TEXT DEFAULT NULL, image_url TEXT DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, feed_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1491BAF151A5BC03 ON "feed_items" (feed_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_feed_item_guid ON "feed_items" (feed_id, guid)');
        $this->addSql('CREATE TABLE "feeds" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(500) NOT NULL, title VARCHAR(255) DEFAULT NULL, last_checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5A29F52FF47645AE ON "feeds" (url)');
        $this->addSql('CREATE TABLE "users" (id BIGINT NOT NULL, username VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_feeds (user_id BIGINT NOT NULL, feed_id INT NOT NULL, PRIMARY KEY (user_id, feed_id))');
        $this->addSql('CREATE INDEX IDX_B8EB0E77A76ED395 ON user_feeds (user_id)');
        $this->addSql('CREATE INDEX IDX_B8EB0E7751A5BC03 ON user_feeds (feed_id)');
        $this->addSql('ALTER TABLE "feed_items" ADD CONSTRAINT FK_1491BAF151A5BC03 FOREIGN KEY (feed_id) REFERENCES "feeds" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_feeds ADD CONSTRAINT FK_B8EB0E77A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_feeds ADD CONSTRAINT FK_B8EB0E7751A5BC03 FOREIGN KEY (feed_id) REFERENCES "feeds" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "feed_items" DROP CONSTRAINT FK_1491BAF151A5BC03');
        $this->addSql('ALTER TABLE user_feeds DROP CONSTRAINT FK_B8EB0E77A76ED395');
        $this->addSql('ALTER TABLE user_feeds DROP CONSTRAINT FK_B8EB0E7751A5BC03');
        $this->addSql('DROP TABLE "feed_items"');
        $this->addSql('DROP TABLE "feeds"');
        $this->addSql('DROP TABLE "users"');
        $this->addSql('DROP TABLE user_feeds');
    }
}
