services:
  app:
    image: ghcr.io/moocluck/picky-rss:latest
    container_name: picky_rss_app
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      APP_ENV: prod
      APP_CACHE_DIR: /tmp/picky_rss/cache
      APP_LOG_DIR: /tmp/picky_rss/log
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: picky_rss_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-picky_rss}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
